import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

import { Header } from "./components/header";
import { HeaderMobile } from "./components/header-mobile";

export const metadata = {
  title: "Future of Work Council",
  description: "Generated by create next app",
  name: "viewport",
  content: "initial-scale=1.0, width=device-width",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="row g-0 h-100">
          <div className="col-12 d-md-none">
            <HeaderMobile />
          </div>
          <div className="d-none col-md-3 d-md-flex">
            <Header />
          </div>
          <div className="col-12 col-md-9">{children}</div>
        </div>
      </body>
    </html>
  );
}
